#!/usr/bin/env bash
# --- Bootstrap HCB2 CORE staging for real-money verification (#35 final pass) ---
# Automates every locally-automatable step of ../headless-company-books/deploy/staging:
#   1. TigerBeetle replica on the HOST at 0.0.0.0:3010 (cluster 0), file-backed.
#   2. .env.staging generation (PG password + cursor signing keys) if absent.
#   3. hcb2-service:staging image build via the sibling build.sh (uses gh auth token).
#   4. docker compose up -d + wait for http://127.0.0.1:8080/readyz == 200.
#
# The ONLY human-gated remainder is the ToGrow Account browser consent (own
# infra, WorkOS dropped per L2-POS-86): login as the canonical demo identity,
# capture the hcb JWT, seed the principal, create the first Company Book —
# printed verbatim as NEXT FOUNDER STEPS at the end.
set -euo pipefail

POS_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
HCB_ROOT="${HFE_HCB_ROOT:-$POS_ROOT/../headless-company-books}"
STAGING_DIR="$HCB_ROOT/deploy/staging"
LOCAL_RUN="$POS_ROOT/.local-run/tigerbeetle"
TB_VERSION="0.17.9"
TB_PORT="3010"

log() { printf '\n\033[1;34m▸ %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

[ -x "$(command -v docker)" ] || die "Docker CLI tidak ditemukan — install Docker Desktop/Rancher dulu."
[ -d "$HCB_ROOT/hcb2/service/src" ] || die "Sibling CORE repo tidak ada di $HCB_ROOT"
docker info >/dev/null 2>&1 || die "Docker daemon tidak berjalan."

# ── 1. TigerBeetle on host ────────────────────────────────────────────────────
mkdir -p "$LOCAL_RUN"
TB_BIN="$LOCAL_RUN/tigerbeetle"
if [ ! -x "$TB_BIN" ]; then
  log "Mengunduh TigerBeetle v$TB_VERSION"
  ARCH="$(uname -m)"
  # Release assets: macOS ships a universal binary; Linux/Windows are per-arch.
  case "$(uname -s)" in
    Darwin) TB_ASSET="tigerbeetle-universal-macos" ;;
    *)      TB_ASSET="tigerbeetle-$([ "$ARCH" = "arm64" ] && echo aarch64 || echo x86_64)" ;;
  esac
  URL="https://github.com/tigerbeetle/tigerbeetle/releases/download/$TB_VERSION/$TB_ASSET.zip"
  curl -fsSL -o "$LOCAL_RUN/tb.zip" "$URL" || die "Gagal mengunduh $URL — cek jaringan."
  unzip -oq "$LOCAL_RUN/tb.zip" -d "$LOCAL_RUN/unzipped"
  find "$LOCAL_RUN/unzipped" -name tigerbeetle -type f -exec cp {} "$TB_BIN" \;
  chmod +x "$TB_BIN"
  rm -rf "$LOCAL_RUN/unzipped" "$LOCAL_RUN/tb.zip"
  echo "  dari: $URL"
fi

if ! nc -z 127.0.0.1 "$TB_PORT" 2>/dev/null; then
  [ -f "$LOCAL_RUN/cluster_0.tigerbeetle" ] || "$TB_BIN" format --cluster=0 --replica=0 --replica-count=1 "$LOCAL_RUN/cluster_0.tigerbeetle"
  log "Menjalankan TigerBeetle cluster 0 di 0.0.0.0:$TB_PORT (nohup)…"
  nohup "$TB_BIN" start --addresses=0.0.0.0:$TB_PORT "$LOCAL_RUN/cluster_0.tigerbeetle" \
    >"$LOCAL_RUN/server.log" 2>&1 &
  sleep 2
else
  echo "TigerBeetle sudah berjalan di :$TB_PORT"
fi
nc -z 127.0.0.1 "$TB_PORT" || die "TigerBeetle gagal listen pada :$TB_PORT (lihat $LOCAL_RUN/server.log)"

# ── 2. .env.staging ───────────────────────────────────────────────────────────
cd "$STAGING_DIR"
if [ ! -f .env.staging ]; then
  log "Generate deploy/staging/.env.staging lokal (placeholder SMTP, kunci acak)…"
  PG_PASS="$(openssl rand -base64 24 | tr '/+' 'Aa')"
  CUR_KEY_ID="staging-key-1"
  CUR_KEY_VAL="$(openssl rand -base64 32)"
  cat > .env.staging <<ENV
STAGING_PG_PASSWORD="$PG_PASS"
STAGING_CURSOR_KEY_ID="$CUR_KEY_ID"
STAGING_CURSOR_KEYS="$CUR_KEY_ID:$CUR_KEY_VAL"
STAGING_SMTP_RELAY="smtp.mailtrap.test"
STAGING_SMTP_FROM="pos-staging@hfeit.test"
STAGING_SMTP_USERNAME="placeholder"
STAGING_SMTP_PASSWORD="placeholder"
STAGING_PUBLIC_BASE_URL="http://localhost:8888"
ENV
  chmod 600 .env.staging
else
  echo ".env.staging sudah ada — dipertahankan."
fi

# ── 3. Build image (skip bila sudah ada) ──────────────────────────────────────
if docker image inspect hcb2-service:staging >/dev/null 2>&1; then
  echo "Image hcb2-service:staging sudah ada — build dilewati."
else
  log "Build hcb2-service:staging (token otomatis dari gh auth)…"
  bash "$HCB_ROOT/scripts/staging/build.sh"
fi

# ── 4. Compose up + readiness ─────────────────────────────────────────────────
# Host-side port avoidance: other Postgres/dev stacks may own 5432/8080.
# Service<->DB traffic stays INSIDE the compose network, so remapping only the
# published host ports is operationally transparent.
# Persisted port choice: recreate-cycles of the stack must not drift mappings
# under an already-running native CORE process.
PORTS_FILE="$POS_ROOT/.local-run/hcb-ports.env"
if [ -f "$PORTS_FILE" ]; then
  # shellcheck disable=SC1090
  source "$PORTS_FILE"
else
  free_port() { local p=$1; while nc -z 127.0.0.1 "$p" 2>/dev/null; do p=$((p+1)); done; echo "$p"; }
  PG_HOST_PORT="$(free_port 15432)"
  echo "PG_HOST_PORT=$PG_HOST_PORT" > "$PORTS_FILE"
fi

cat > "$STAGING_DIR/docker-compose.override.local.yml" <<OV
# Generated by hfe-pos scripts/dev/bootstrap-core-staging.sh — DO NOT COMMIT.
# PG published on a collision-free host port; SERVICE uses host networking so its
# TigerBeetle client sees 127.0.0.1:3010 exactly like scripts/staging/run-native.sh.
services:
  postgres:
    ports: !override ["127.0.0.1:$PG_HOST_PORT:5432"]
OV

log "docker compose up -d postgres…"
docker compose --env-file .env.staging \
  -f docker-compose.yml -f docker-compose.override.local.yml \
  -p hcb-staging up -d postgres

for i in $(seq 1 24); do
  st="$(docker inspect -f '{{.State.Health.Status}}' hcb-staging-postgres-1 2>/dev/null || echo starting)"
  [ "$st" = "healthy" ] && break
  sleep 3
done

# ── 5. Native HCB2 service (io_uring on macOS Docker VM is unavailable, so the
#      Rust TB client MUST run on the host — mirrors scripts/staging/run-native.sh) ──
if curl -sf http://127.0.0.1:8080/readyz >/dev/null 2>&1 || pgrep -f 'books-v2-service' >/dev/null; then
  echo "Native CORE service sudah berjalan."
else
  log "Menyalakan native books-v2-service (debug binary bila ada)…"
  PG_PUB_PORT="$(docker port hcb-staging-postgres-1 5432 | awk -F: '/127.0.0.1/{print $NF}' | head -1)"
  BIN="$HCB_ROOT/hcb2/target/debug/books-v2-service"
  [ -x "$BIN" ] || BIN="$HCB_ROOT/hcb2/target/release/books-v2-service"
  [ -x "$BIN" ] || { log "Binary belum ada — kompilasi release (sekali, ±10 menit)…"; cargo build --release --manifest-path "$HCB_ROOT/hcb2/Cargo.toml" -p books-v2-service; BIN="$HCB_ROOT/hcb2/target/release/books-v2-service"; }
  set -a; source .env.staging; set +a
  # ── Identity: ToGrow Account (WorkOS dropped) — derive live from discovery ──
  DISCOVERY_URL="${TOGROW_DISCOVERY_URL:-http://127.0.0.1:3100/.well-known/openid-configuration}"
  TOGROW_DISC="$(curl -fsS "$DISCOVERY_URL")" || die "ToGrow ID discovery tak terjangkau ($DISCOVERY_URL). Jalankan stack account-togrow dulu."
  export V2_OIDC_ISSUER="$(printf '%s' "$TOGROW_DISC" | python3 -c 'import sys,json;print(json.load(sys.stdin)["issuer"])')"
  export V2_OIDC_JWKS_URI="$(printf '%s' "$TOGROW_DISC" | python3 -c 'import sys,json;print(json.load(sys.stdin)["jwks_uri"])')"
  # The registered federation client ('Hfe CORE Local Demo') carries the hcb:access scope.
  TOGROW_CLIENT_ID="${TOGROW_CLIENT_ID:-xQHOwumWWJilqUj_yR6RVc1FjBvvjZMUIkt2jC_In2k}"
  export V2_OIDC_AUDIENCE="$TOGROW_CLIENT_ID"
  export V2_OIDC_INTERACTIVE_CLIENT_IDS="$TOGROW_CLIENT_ID"
  export V2_OIDC_REQUIRED_SCOPE="openid"
  export V2_OIDC_HUMAN_CLAIM="sub" V2_OIDC_HUMAN_VALUES="*"
  export V2_DEPLOYMENT_ENVIRONMENT="staging"
  export V2_DATABASE_URL="postgres://company_books:${STAGING_PG_PASSWORD}@127.0.0.1:${PG_PUB_PORT:-15432}/company_books"
  export V2_BIND_ADDRESS="127.0.0.1:8080"
  export V2_TIGERBEETLE_ADDRESSES="127.0.0.1:$TB_PORT" V2_TIGERBEETLE_CLUSTER_ID="0"
  export V2_OIDC_METADATA_TTL_SECONDS="300" V2_OIDC_REQUEST_TIMEOUT_SECONDS="5"
  export V2_CURSOR_ACTIVE_KEY_ID="staging-key-1"
  export V2_CURSOR_KEYS="$STAGING_CURSOR_KEYS"
  export V2_SMTP_RELAY="localhost" V2_SMTP_PORT="587" V2_SMTP_FROM="noreply@staging.local" V2_SMTP_USERNAME="placeholder" V2_SMTP_PASSWORD="placeholder"
  export V2_PUBLIC_APP_BASE_URL="http://127.0.0.1:8080" V2_INVITATION_TTL_HOURS="72"
  export V2_DISPATCH_WORKER_ID="hcb-staging-dispatcher" V2_DISPATCH_POLL_INTERVAL_MS="5000"
  export V2_READINESS_TIMEOUT_MS="60000" V2_SHUTDOWN_TIMEOUT_SECONDS="30"
  mkdir -p "$POS_ROOT/.local-run"
  nohup "$BIN" >"$POS_ROOT/.local-run/core-service.log" 2>&1 &
fi

for i in $(seq 1 40); do
  code="$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:8080/readyz || true)"
  [ "$code" = "200" ] && break
  [ $((i % 6)) -eq 0 ] && echo "  menunggu /readyz… ($i)"
  sleep 5
done
curl -fsS http://127.0.0.1:8080/readyz >/dev/null || die "/readyz belum hijau. Log: $POS_ROOT/.local-run/core-service.log"

log "STACK HIDUP ✔ — TIGERBEETLE (:3010), POSTGRES (compose), CORE (/readyz 200 @ :8080)"

# Identity values for the founder checklist (ToGrow Account — WorkOS dropped)
TG_ISSUER="$(curl -fsS "${TOGROW_DISCOVERY_URL:-http://127.0.0.1:3100/.well-known/openid-configuration}" | python3 -c 'import sys,json;print(json.load(sys.stdin)["issuer"])' 2>/dev/null || echo '<jalankan stack account-togrow dulu>')"
TG_CLIENT="${TOGROW_CLIENT_ID:-xQHOwumWWJilqUj_yR6RVc1FjBvvjZMUIkt2jC_In2k}"

cat <<NEXT

════════════════════════════════════════════════════════════════
 LANGKAH FOUNDER — identitas ToGrow Account (WorkOS di-drop)
════════════════════════════════════════════════════════════════
Stack CORE lokal sudah hidup. Tinggal satu sesi browser:

1) Jalankan POS dev server lalu login via ToGrow:
     cd "$POS_ROOT" && npm run dev          # http://localhost:5173
   Masuk sebagai flagship.cafe@demo.hfeit.test.
   Klien federasi resmi: "Hfe CORE Local Demo"
     issuer : $TG_ISSUER
     client : $TG_CLIENT
     scope  : openid profile email hcb:access

2) Kalau lebih suka mint token manual, buka URL ini di browser
   (login ToGrow → consent → copy `code` dari callback):
     $TG_ISSUER/v1/oauth/authorize?client_id=$TG_CLIENT&redirect_uri=http://localhost:5173/auth/callback&response_type=code&scope=openid%20profile%20email%20hcb:access

3) Tempelkan JWT (`hcb-token`) atau subject user ke agent sesi ini —
   seeding principals + create Company Book + transaksi uang-nyata
   pertama (badge LIVE pertama) diselesaikan otomatis setelahnya.
════════════════════════════════════════════════════════════════
NEXT
